###

GET http://localhost:8082

###
# Authorization: Basic username:password
###

#POST http://localhost:8082/oauth/token
#Content-Type: application/x-www-form-urlencoded
#Authorization: Basic client-id-test:client-secret-test
#
#grant_type=password&username=usuario1&password=654321
#// informações de um usuário



###
# Consulta todos os usuarios
###

GET http://localhost:8082/usuarios

###
# Consulta usuario por id
###

GET http://localhost:8082/usuarios/4

###
# Cadastra usuario
###

POST http://localhost:8082/usuarios
Content-Type: application/json

{
  "nome": "Leonardo Junger",
  "email": "leonardo@junger.com",
  "password": "123456",
  "username": "leonardojunger"
}

###

PUT http://localhost:8082/usuarios/7
Content-Type: application/json

{
  "nome": "Giselle Estevez",
  "username": "giselleestevez",
  "email": "giselle@estevez.com",
  "password": "123456"
}

###

DELETE http://localhost:8082/usuarios/9

###
# Consulta todos os Produto
###

GET http://localhost:8082/produtos
#Authorization: Bearer dba4Qli-tYWyGHKm4e0LnKWa5Lg

###
# Consulta Produto por id
###

GET  http://localhost:8082/produtos/2

###
# Gerar Csv do Produto por id
###

GET  http://localhost:8082/produtos/gerarCsv/1

###
# Cadastrar um Produto
###

POST http://localhost:8082/produtos
Content-Type: application/json

{
  "nome": "Mochila",
  "marca": "Nike",
  "valor": "R$ 99,99"
}

###

PUT http://localhost:8082/produtos/2
Content-Type: application/json

{
  "nome": "monitor",
  "marca": "aoc",
  "valor": "R$ 768,98"
}

###

DELETE http://localhost:8082/produtos/6

###

GET http://localhost:8082/bucket/